default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password:  #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development
